version: '2'

services:
  ventas:
    build: .
    container_name: ventas
    command: /bin/sh -c "rm -f /var/www/sistema_ventas/tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/var/www/sistema_ventas
    ports:
      - "3000:3000"
    links:
      - db_ventas
  db_ventas:
    image: mysql:5.6
    container_name: db_ventas
    ports:
      - "3306:3306"
    volumes:
      - './data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
